console.log("🔥 HAAG FAMILY MISSIONARY MAP v4 LOADED");

const SHEET_ID = "15BJwH_54gL9fWGCtg0FOwF_qYy4mAm7KWN1LVnSBl5w";
const MISSIONARY_SHEET_NAME = "Form Responses 1";
const COORDINATES_SHEET_NAME = "Coordinates";

let allMissionaries = [];
let allMarkers = [];
let selectedYears = new Set();
let activeSearch = "";

const map = L.map("map", { zoomControl: false, worldCopyJump: true }).setView([25, 0], 2);

const streetLayer = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}", { attribution: "Tiles © Esri" });
const satelliteLayer = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}", { attribution: "Imagery © Esri" });
const terrainLayer = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}", { attribution: "Tiles © Esri" });
streetLayer.addTo(map);
L.control.zoom({ position: "bottomright" }).addTo(map);
L.control.layers({ Street: streetLayer, Satellite: satelliteLayer, Terrain: terrainLayer }, null, { position: "bottomright", collapsed: false }).addTo(map);

const CONTINENTS = {"United States":"North America",USA:"North America",US:"North America",Brazil:"South America",Denmark:"Europe",Germany:"Europe",Italy:"Europe",France:"Europe",Spain:"Europe",Mexico:"North America",Canada:"North America",England:"Europe","United Kingdom":"Europe",Argentina:"South America",Chile:"South America",Peru:"South America",Colombia:"South America",Philippines:"Asia",Japan:"Asia",Australia:"Oceania","New Zealand":"Oceania"};

function normalize(v){return String(v||"").replace(/\s+/g," ").trim().toLowerCase();}
function normalizeNoAccent(v){return normalize(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
function cleanHeader(v){return String(v||"").replace(/\s+/g," ").trim();}
function getValue(row,names){for(const n of names){if(row[n]!==undefined&&row[n]!=="")return row[n];}const keys=Object.keys(row);for(const n of names){const k=keys.find(x=>normalize(x)===normalize(n));if(k&&row[k]!=="")return row[k];}return "";}
async function loadSheet(sheetName){const url=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent(sheetName)}`;const res=await fetch(url);const text=await res.text();const json=JSON.parse(text.substring(47).slice(0,-2));const cols=json.table.cols.map(c=>cleanHeader(c.label));return json.table.rows.map(row=>{const obj={};row.c.forEach((cell,i)=>{obj[cols[i]]=cell?cell.v:""});return obj;});}

function getName(m){return getValue(m,["Missionary Name (First Last) (e.g., Dawn Hollingsworth)","Missionary Name (First Last)","Missionary Name","Name"])}
function getSex(m){return getValue(m,["Biological Sex","Sex","Gender"])}
function getRelation(m){return getValue(m,["Who is your Haag relation?","Haag relation","Relation"])}
function getRelationship(m){return getValue(m,["What is your relationship to Elva and Darrell?","Relationship to Elva and Darrell"])}
function getMissionName(m){return getValue(m,["Official Mission name (Ex: Maryland Baltimore)","Official Mission Name","Official Mission name","Mission Name"])}
function getCity(m){return getValue(m,["City","Mission City"])}
function getState(m){return getValue(m,["State/Region","State","Mission State"])}
function getCountry(m){return getValue(m,["Country","Mission Country"])}
function getLanguage(m){return getValue(m,["Assigned Language(s)","Assigned Languages","Language","Languages"])}
function getStartDate(m){return getValue(m,["Start Date (MM/YYYY)","Start Date"])}
function getEndDate(m){return getValue(m,["End Date (MM/YYYY)","End Date"])}
function getPresidents(m){return getValue(m,["Mission President Names (Ex: President and Sister Piros; President and Sister Varner)","Mission President Names","Mission Presidents"])}
function getSpouse(m){return getValue(m,["Your Spouse's Name (If Applicable)","Spouse","Spouse Name"])}

function getTitle(sex,name,language){if(sex!=="Female")return `Elder ${name||""}`;const first=String(language||"English").split(",")[0].trim();const sister={Spanish:"Hermana",Italian:"Sorella",French:"Sœur"};return `${sister[first]||"Sister"} ${name||""}`;}
function getColor(sex){return sex==="Female"?"#ec4899":"#2563eb";}
function isInLaw(m){return normalize(getRelationship(m)).includes("in-law");}
function parseMonthYear(v){if(!v)return null;const p=String(v).trim().split("/");if(p.length!==2)return null;const month=Number(p[0]),year=Number(p[1]);if(!month||!year||month<1||month>12)return null;return {month,year};}
function formatMissionDate(v){const p=parseMonthYear(v);if(!p)return v||"";const months=["January","February","March","April","May","June","July","August","September","October","November","December"];return `${months[p.month-1]} ${p.year}`;}
function isCurrentlyServing(m){const e=parseMonthYear(getEndDate(m));if(!e)return false;return new Date(e.year,e.month,0)>=new Date();}
function missionLength(start,end){const s=parseMonthYear(start),e=parseMonthYear(end);if(!s||!e)return "";const months=(e.year-s.year)*12+(e.month-s.month)+1;return `${months} month${months===1?"":"s"}`;}
function formatMissionDates(m){const s=getStartDate(m),e=getEndDate(m);if(isCurrentlyServing(m))return `<div class="card-date-main">${formatMissionDate(s)} – Present</div><div class="currently-serving">✓ Currently Serving</div>`;return `<div class="card-date-main">${formatMissionDate(s)} – ${formatMissionDate(e)}</div><div class="mission-length">${missionLength(s,e)}</div>`;}
function formatPresidents(t){return String(t||"").split(";").map(x=>x.trim()).filter(Boolean).join("<br>");}
function missionaryYears(m){const s=parseMonthYear(getStartDate(m)),e=parseMonthYear(getEndDate(m));if(!s||!e)return [];const arr=[];for(let y=s.year;y<=e.year;y++)arr.push(y);return arr;}

function getFlagImage(country,state){const c=String(country||"").replace(/\s+/g," ").trim();const st=String(state||"").replace(/\s+/g," ").trim();const key=normalizeNoAccent(st);const us={maryland:"https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg",louisiana:"https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_Louisiana.svg",utah:"https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg",ohio:"https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg",washington:"https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg",oregon:"https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Oregon.svg",connecticut:"https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg"};const brazilFlags = {
  goias: "https://upload.wikimedia.org/wikipedia/commons/b/be/Bandeira_de_Goi%C3%A1s.svg",
  "rio de janeiro": "https://upload.wikimedia.org/wikipedia/commons/7/73/Bandeira_do_estado_do_Rio_de_Janeiro.svg"
};if(["United States","USA","US"].includes(c)&&us[key])return `<img class="flag-img" src="${us[key]}" alt="${st} flag">`;if(c==="Brazil"&&br[key])return `<img class="flag-img" src="${br[key]}" alt="${st} flag">`;const codes={"United States":"us",USA:"us",US:"us",Brazil:"br",Denmark:"dk",Germany:"de",Italy:"it",France:"fr",Spain:"es",Mexico:"mx",Canada:"ca",England:"gb","United Kingdom":"gb",Argentina:"ar",Chile:"cl",Peru:"pe",Colombia:"co",Philippines:"ph",Japan:"jp",Australia:"au","New Zealand":"nz"};const code=codes[c];return code?`<img class="flag-img" src="https://flagcdn.com/w80/${code}.png" alt="${c} flag">`:`<div class="flag-placeholder">🌍</div>`;}

function missionaryPopupHtml(m){const lang=getLanguage(m),pres=getPresidents(m),spouse=getSpouse(m);return `<div class="leaflet-mission-popup single-missionary-popup"><h2>${getTitle(getSex(m),getName(m),lang)}</h2><div class="card-divider"></div><div class="card-location-small">${getFlagImage(getCountry(m),getState(m))}<div><div class="card-mission">${getMissionName(m)||""}</div>${lang?`<div class="popup-language">${lang}</div>`:""}</div></div><div class="card-dates">${formatMissionDates(m)}</div>${pres?`<div class="card-presidents">${formatPresidents(pres)}</div>`:""}${spouse?`<div class="card-spouse">Married to ${spouse}</div>`:""}</div>`;}
function groupPopupHtml(group){const f=group[0];const langs=new Set(group.map(m=>getLanguage(m)).filter(Boolean));return `<div class="leaflet-mission-popup group-mission-popup"><h2>${getMissionName(f)}</h2><div class="card-divider"></div><div class="card-location-small">${getFlagImage(getCountry(f),getState(f))}<div><div class="card-mission">${group.length} missionaries served here</div>${langs.size?`<div class="popup-language">${Array.from(langs).join(", ")}</div>`:""}</div></div><div class="missionary-list">${group.map((m,i)=>`<button type="button" class="missionary-list-item" data-index="${i}"><strong>${getTitle(getSex(m),getName(m),getLanguage(m))}</strong><span>${formatMissionDate(getStartDate(m))} – ${isCurrentlyServing(m)?"Present":formatMissionDate(getEndDate(m))}</span></button>`).join("")}</div></div>`;}
function showDetailPreview(m,anchor){const p=document.getElementById("detailPreview");if(!p||!anchor)return;p.innerHTML=missionaryPopupHtml(m);p.classList.remove("hidden");const r=anchor.getBoundingClientRect();let left=r.right+14,top=r.top;p.style.left=`${left}px`;p.style.top=`${top}px`;const pr=p.getBoundingClientRect();if(pr.right>window.innerWidth-12)left=r.left-pr.width-14;if(pr.bottom>window.innerHeight-12)top=window.innerHeight-pr.height-12;if(top<12)top=12;p.style.left=`${left}px`;p.style.top=`${top}px`;}
function hideDetailPreview(){const p=document.getElementById("detailPreview");if(!p)return;p.classList.add("hidden");p.innerHTML="";document.querySelectorAll(".missionary-list-item.active").forEach(b=>b.classList.remove("active"));}
function handleOutsidePreviewClick(e){const p=document.getElementById("detailPreview");if(!p||p.classList.contains("hidden"))return;if(!p.contains(e.target)&&!e.target.closest(".missionary-list-item"))hideDetailPreview();}
function setupGroupPopupEvents(marker,group){marker.on("popupopen",ev=>{setTimeout(()=>{const el=ev.popup.getElement();if(!el)return;el.querySelectorAll(".missionary-list-item").forEach(btn=>{const m=group[Number(btn.dataset.index)];const show=()=>{document.querySelectorAll(".missionary-list-item.active").forEach(b=>b.classList.remove("active"));btn.classList.add("active");showDetailPreview(m,btn);};btn.addEventListener("mouseenter",show);btn.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();show();});});document.addEventListener("click",handleOutsidePreviewClick);},0);});marker.on("popupclose",()=>{hideDetailPreview();document.removeEventListener("click",handleOutsidePreviewClick);});}
function bindMarkerPopup(marker,group){if(group.length===1){marker.bindPopup(missionaryPopupHtml(group[0]),{closeButton:true,autoPan:true,maxWidth:360,className:"haag-leaflet-popup"});}else{marker.bindPopup(groupPopupHtml(group),{closeButton:true,autoPan:true,maxWidth:380,className:"haag-leaflet-popup"});setupGroupPopupEvents(marker,group);}marker.on("mouseover",()=>marker.openPopup());marker.on("click",()=>marker.openPopup());}
function createMarkerIcon(group){const count=group.length,hasMale=group.some(m=>getSex(m)!=="Female"),hasFemale=group.some(m=>getSex(m)==="Female"),hasCurrent=group.some(isCurrentlyServing),hasInLaw=group.some(isInLaw);let color=getColor(getSex(group[0]));if(hasMale&&hasFemale)color="#7c3aed";let inner="";if(count>1)inner=`<span class="marker-number">${count}</span>`;else if(hasCurrent)inner=`<span class="marker-check">✓</span>`;const cls=["mission-marker",count>1?"duplicate-marker":"",hasInLaw&&count===1?"heart-marker":"dot-marker"].join(" ");return L.divIcon({className:"custom-marker",html:`<div class="${cls}" style="--marker-color:${color}">${inner}</div>`,iconSize:[34,34],iconAnchor:[17,17],popupAnchor:[0,-14]});}
function clearMarkers(){allMarkers.forEach(m=>map.removeLayer(m));allMarkers=[];}
function getFilteredData(){return allMissionaries.filter(m=>matchesFamily(m)&&matchesSex(m)&&matchesCurrent(m)&&matchesInLaw(m)&&matchesSearch(m)&&matchesYears(m));}
function matchesFamily(m){const s=document.getElementById("familyFilter").value;return s==="all"||normalize(getRelation(m)).includes(normalize(s));}
function matchesSex(m){return getSex(m)==="Female"?document.getElementById("showSisters").checked:document.getElementById("showElders").checked;}
function matchesCurrent(m){return document.getElementById("showCurrent").checked||!isCurrentlyServing(m);}
function matchesInLaw(m){return document.getElementById("showInLaws").checked||!isInLaw(m);}
function matchesSearch(m){if(!activeSearch)return true;const h=[getName(m),getMissionName(m),getCity(m),getState(m),getCountry(m),getLanguage(m),getPresidents(m),getSpouse(m),getRelation(m)].join(" ");return normalize(h).includes(normalize(activeSearch));}
function matchesYears(m){return selectedYears.size===0||missionaryYears(m).some(y=>selectedYears.has(y));}
function groupByMission(data){const groups={};data.forEach(m=>{if(!m.coords)return;const k=normalize(getMissionName(m));if(!groups[k])groups[k]=[];groups[k].push(m);});return Object.values(groups);}
function drawMarkers(){clearMarkers();hideDetailPreview();const data=getFilteredData();updateStats(data);const groups=groupByMission(data);const bounds=[];groups.forEach(g=>{const c=g[0].coords;const marker=L.marker([c.lat,c.lng],{icon:createMarkerIcon(g)}).addTo(map);bindMarkerPopup(marker,g);allMarkers.push(marker);bounds.push([c.lat,c.lng]);});if(bounds.length>0)map.fitBounds(bounds,{padding:[80,80],maxZoom:5});}
function countItems(values){const c={};values.filter(Boolean).forEach(v=>{const k=String(v).trim();c[k]=(c[k]||0)+1;});return c;}
function topItem(values){const e=Object.entries(countItems(values));if(!e.length)return"--";e.sort((a,b)=>b[1]-a[1]);return `${e[0][0]} (${e[0][1]})`;}
function getLanguageList(m){return String(getLanguage(m)||"").split(/,|;|\/|&/).map(x=>x.trim()).filter(Boolean);}
function updateStats(data){document.getElementById("totalMissionaries").textContent=data.length;document.getElementById("totalElders").textContent=data.filter(m=>getSex(m)!=="Female").length;document.getElementById("totalSisters").textContent=data.filter(m=>getSex(m)==="Female").length;document.getElementById("currentMissionaries").textContent=data.filter(isCurrentlyServing).length;document.getElementById("countriesServed").textContent=new Set(data.map(getCountry).filter(Boolean)).size;document.getElementById("totalContinents").textContent=new Set(data.map(m=>CONTINENTS[getCountry(m)]).filter(Boolean)).size;const langs=new Set();data.forEach(m=>getLanguageList(m).forEach(l=>langs.add(l)));document.getElementById("totalLanguages").textContent=langs.size;const missionCounts=countItems(data.map(getMissionName));document.getElementById("duplicateMissions").textContent=Object.values(missionCounts).filter(n=>n>1).length;document.getElementById("topLanguage").textContent=topItem(data.flatMap(getLanguageList));document.getElementById("topCountry").textContent=topItem(data.map(getCountry));}
function buildYearCheckboxes(){const box=document.getElementById("yearCheckboxes");const years=new Set();allMissionaries.forEach(m=>missionaryYears(m).forEach(y=>years.add(y)));box.innerHTML=Array.from(years).sort((a,b)=>b-a).map(y=>`<label class="year-option"><input type="checkbox" value="${y}"> ${y}</label>`).join("");box.querySelectorAll("input").forEach(input=>input.addEventListener("change",()=>{const y=Number(input.value);input.checked?selectedYears.add(y):selectedYears.delete(y);drawMarkers();}));}
function setupControls(){["showElders","showSisters","showCurrent","showInLaws","familyFilter"].forEach(id=>document.getElementById(id).addEventListener("change",drawMarkers));document.getElementById("searchInput").addEventListener("input",e=>{activeSearch=e.target.value;drawMarkers();});document.getElementById("clearYears").addEventListener("click",()=>{selectedYears.clear();document.querySelectorAll("#yearCheckboxes input").forEach(i=>i.checked=false);drawMarkers();});document.getElementById("menuToggle").addEventListener("click",()=>{menuPanel.classList.remove("hidden-panel");menuToggle.style.display="none";});document.getElementById("menuClose").addEventListener("click",()=>{menuPanel.classList.add("hidden-panel");menuToggle.style.display="block";});document.getElementById("statsToggle").addEventListener("click",()=>{statsPanel.classList.remove("hidden-panel");statsToggle.style.display="none";});document.getElementById("statsClose").addEventListener("click",()=>{statsPanel.classList.add("hidden-panel");statsToggle.style.display="block";});menuToggle.style.display="none";statsToggle.style.display="none";}
async function buildMap(){const missionaries=await loadSheet(MISSIONARY_SHEET_NAME);const coordinates=await loadSheet(COORDINATES_SHEET_NAME);const lookup={};coordinates.forEach(r=>{const mission=getMissionName(r);const lat=Number(getValue(r,["Latitude","Lat"]));const lng=Number(getValue(r,["Longitude","Long","Lng"]));if(mission&&!isNaN(lat)&&!isNaN(lng))lookup[normalize(mission)]={lat,lng};});allMissionaries=missionaries.map(m=>{const mission=getMissionName(m);const coords=lookup[normalize(mission)]||null;if(!coords)console.warn("No coordinates found for mission:",mission);return {...m,coords};});buildYearCheckboxes();setupControls();drawMarkers();}
buildMap();
